/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.twitter.sdk.android.core;

public final class R {
    public static final class attr {
        public static final int tw__image_aspect_ratio = 0x7f0101b3;
        public static final int tw__image_dimension_to_adjust = 0x7f0101b4;
    }
    public static final class color {
        public static final int tw__blue_default = 0x7f0e0079;
        public static final int tw__blue_pressed = 0x7f0e007a;
        public static final int tw__blue_pressed_light = 0x7f0e007b;
        public static final int tw__light_gray = 0x7f0e0085;
        public static final int tw__solid_white = 0x7f0e0088;
        public static final int tw__transparent = 0x7f0e0089;
    }
    public static final class dimen {
        public static final int tw__btn_bar_margin_left = 0x7f0a00de;
        public static final int tw__btn_bar_margin_right = 0x7f0a00df;
        public static final int tw__login_btn_drawable_padding = 0x7f0a0001;
        public static final int tw__login_btn_height = 0x7f0a0002;
        public static final int tw__login_btn_left_padding = 0x7f0a0003;
        public static final int tw__login_btn_radius = 0x7f0a0115;
        public static final int tw__login_btn_right_padding = 0x7f0a0004;
        public static final int tw__login_btn_text_size = 0x7f0a0005;
        public static final int tw__padding_permission_horizontal_container = 0x7f0a0021;
        public static final int tw__padding_permission_vertical_container = 0x7f0a0118;
        public static final int tw__permission_description_text_size = 0x7f0a0119;
        public static final int tw__permission_title_text_size = 0x7f0a011a;
    }
    public static final class drawable {
        public static final int tw__ic_logo_default = 0x7f020110;
        public static final int tw__login_btn = 0x7f020125;
        public static final int tw__login_btn_default = 0x7f020126;
        public static final int tw__login_btn_default_light = 0x7f020127;
        public static final int tw__login_btn_disabled = 0x7f020128;
        public static final int tw__login_btn_light = 0x7f020129;
        public static final int tw__login_btn_pressed = 0x7f02012a;
        public static final int tw__login_btn_pressed_light = 0x7f02012b;
        public static final int tw__login_btn_text_color_light = 0x7f02012c;
        public static final int tw__share_email_header = 0x7f020131;
        public static final int tw__transparent = 0x7f020132;
    }
    public static final class id {
        public static final int height = 0x7f100032;
        public static final int imageView = 0x7f1000e1;
        public static final int tw__allow_btn = 0x7f100107;
        public static final int tw__not_now_btn = 0x7f100106;
        public static final int tw__share_email_desc = 0x7f100105;
        public static final int tw__spinner = 0x7f100104;
        public static final int tw__web_view = 0x7f100103;
        public static final int width = 0x7f100033;
    }
    public static final class layout {
        public static final int tw__activity_oauth = 0x7f040073;
        public static final int tw__activity_share_email = 0x7f040074;
    }
    public static final class raw {
        public static final int tw__cacerts = 0x7f070000;
    }
    public static final class string {
        public static final int kit_name = 0x7f08008c;
        public static final int tw__allow_btn_txt = 0x7f080039;
        public static final int tw__login_btn_txt = 0x7f080040;
        public static final int tw__not_now_btn_txt = 0x7f080042;
        public static final int tw__share_email_desc = 0x7f08004b;
        public static final int tw__share_email_title = 0x7f08004c;
    }
    public static final class style {
        public static final int tw__Button = 0x7f0b01d8;
        public static final int tw__ButtonBar = 0x7f0b01da;
        public static final int tw__Button_Light = 0x7f0b01d9;
        public static final int tw__Permission_Container = 0x7f0b01e8;
        public static final int tw__Permission_Description = 0x7f0b01e9;
        public static final int tw__Permission_Title = 0x7f0b01ea;
    }
    public static final class styleable {
        public static final int[] tw__AspectRatioImageView = { 0x7f0101b3, 0x7f0101b4 };
        public static final int tw__AspectRatioImageView_tw__image_aspect_ratio = 0;
        public static final int tw__AspectRatioImageView_tw__image_dimension_to_adjust = 1;
    }
}
