/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.twitter.sdk.android.tweetcomposer;

public final class R {
    public static final class attr {
        public static final int tw__image_aspect_ratio = 0x7f0101b3;
        public static final int tw__image_dimension_to_adjust = 0x7f0101b4;
        public static final int tw__twitter_logo = 0x7f01004c;
    }
    public static final class color {
        public static final int tw__blue_default = 0x7f0e0079;
        public static final int tw__blue_pressed = 0x7f0e007a;
        public static final int tw__blue_pressed_light = 0x7f0e007b;
        public static final int tw__composer_black = 0x7f0e007c;
        public static final int tw__composer_blue = 0x7f0e007d;
        public static final int tw__composer_blue_text = 0x7f0e007e;
        public static final int tw__composer_deep_gray = 0x7f0e007f;
        public static final int tw__composer_light_gray = 0x7f0e0080;
        public static final int tw__composer_red = 0x7f0e0081;
        public static final int tw__composer_white = 0x7f0e0082;
        public static final int tw__light_gray = 0x7f0e0085;
        public static final int tw__solid_white = 0x7f0e0088;
        public static final int tw__transparent = 0x7f0e0089;
    }
    public static final class dimen {
        public static final int tw__btn_bar_margin_left = 0x7f0a00de;
        public static final int tw__btn_bar_margin_right = 0x7f0a00df;
        public static final int tw__card_font_size_medium = 0x7f0a00e0;
        public static final int tw__card_font_size_small = 0x7f0a00e1;
        public static final int tw__card_maximum_width = 0x7f0a00e2;
        public static final int tw__card_radius_medium = 0x7f0a00e3;
        public static final int tw__card_radius_small = 0x7f0a00e4;
        public static final int tw__card_spacing_large = 0x7f0a00e5;
        public static final int tw__card_spacing_medium = 0x7f0a00e6;
        public static final int tw__card_spacing_small = 0x7f0a00e7;
        public static final int tw__composer_avatar_size = 0x7f0a0104;
        public static final int tw__composer_char_count_height = 0x7f0a0105;
        public static final int tw__composer_close_size = 0x7f0a0106;
        public static final int tw__composer_divider_height = 0x7f0a0107;
        public static final int tw__composer_font_size_small = 0x7f0a0108;
        public static final int tw__composer_logo_height = 0x7f0a0109;
        public static final int tw__composer_logo_width = 0x7f0a010a;
        public static final int tw__composer_spacing_large = 0x7f0a010b;
        public static final int tw__composer_spacing_medium = 0x7f0a010c;
        public static final int tw__composer_spacing_small = 0x7f0a010d;
        public static final int tw__composer_tweet_btn_height = 0x7f0a010e;
        public static final int tw__composer_tweet_btn_radius = 0x7f0a010f;
        public static final int tw__login_btn_drawable_padding = 0x7f0a0001;
        public static final int tw__login_btn_height = 0x7f0a0002;
        public static final int tw__login_btn_left_padding = 0x7f0a0003;
        public static final int tw__login_btn_radius = 0x7f0a0115;
        public static final int tw__login_btn_right_padding = 0x7f0a0004;
        public static final int tw__login_btn_text_size = 0x7f0a0005;
        public static final int tw__padding_permission_horizontal_container = 0x7f0a0021;
        public static final int tw__padding_permission_vertical_container = 0x7f0a0118;
        public static final int tw__permission_description_text_size = 0x7f0a0119;
        public static final int tw__permission_title_text_size = 0x7f0a011a;
    }
    public static final class drawable {
        public static final int tw__app_info_layout_border = 0x7f0200c9;
        public static final int tw__btn_composer_tweet = 0x7f0200cb;
        public static final int tw__composer_close = 0x7f0200cd;
        public static final int tw__composer_logo_blue = 0x7f0200ce;
        public static final int tw__composer_logo_white = 0x7f0200cf;
        public static final int tw__ic_logo_default = 0x7f020110;
        public static final int tw__install_button_border = 0x7f020123;
        public static final int tw__login_btn = 0x7f020125;
        public static final int tw__login_btn_default = 0x7f020126;
        public static final int tw__login_btn_default_light = 0x7f020127;
        public static final int tw__login_btn_disabled = 0x7f020128;
        public static final int tw__login_btn_light = 0x7f020129;
        public static final int tw__login_btn_pressed = 0x7f02012a;
        public static final int tw__login_btn_pressed_light = 0x7f02012b;
        public static final int tw__login_btn_text_color_light = 0x7f02012c;
        public static final int tw__share_email_header = 0x7f020131;
        public static final int tw__transparent = 0x7f020132;
    }
    public static final class id {
        public static final int height = 0x7f100032;
        public static final int imageView = 0x7f1000e1;
        public static final int tw__allow_btn = 0x7f100107;
        public static final int tw__app_image = 0x7f100108;
        public static final int tw__app_info_layout = 0x7f100109;
        public static final int tw__app_install_button = 0x7f10010a;
        public static final int tw__app_name = 0x7f10010b;
        public static final int tw__app_store_name = 0x7f10010c;
        public static final int tw__author_avatar = 0x7f100110;
        public static final int tw__card_view = 0x7f100114;
        public static final int tw__char_count = 0x7f100117;
        public static final int tw__composer_close = 0x7f10010e;
        public static final int tw__composer_header = 0x7f10010d;
        public static final int tw__composer_profile_divider = 0x7f100111;
        public static final int tw__composer_scroll_view = 0x7f100112;
        public static final int tw__composer_toolbar = 0x7f100116;
        public static final int tw__composer_toolbar_divider = 0x7f100115;
        public static final int tw__composer_view = 0x7f100102;
        public static final int tw__edit_tweet = 0x7f100113;
        public static final int tw__not_now_btn = 0x7f100106;
        public static final int tw__post_tweet = 0x7f100118;
        public static final int tw__share_email_desc = 0x7f100105;
        public static final int tw__spinner = 0x7f100104;
        public static final int tw__twitter_logo = 0x7f10010f;
        public static final int tw__web_view = 0x7f100103;
        public static final int width = 0x7f100033;
    }
    public static final class layout {
        public static final int tw__activity_composer = 0x7f040072;
        public static final int tw__activity_oauth = 0x7f040073;
        public static final int tw__activity_share_email = 0x7f040074;
        public static final int tw__app_card = 0x7f040075;
        public static final int tw__composer_view = 0x7f040076;
    }
    public static final class raw {
        public static final int tw__cacerts = 0x7f070000;
    }
    public static final class string {
        public static final int kit_name = 0x7f08008c;
        public static final int tw__allow_btn_txt = 0x7f080039;
        public static final int tw__composer_hint = 0x7f08003a;
        public static final int tw__install = 0x7f08003c;
        public static final int tw__login_btn_txt = 0x7f080040;
        public static final int tw__max_tweet_chars = 0x7f080041;
        public static final int tw__not_now_btn_txt = 0x7f080042;
        public static final int tw__play_store = 0x7f0800af;
        public static final int tw__post_tweet = 0x7f080045;
        public static final int tw__share_email_desc = 0x7f08004b;
        public static final int tw__share_email_title = 0x7f08004c;
    }
    public static final class style {
        public static final int ComposerDark = 0x7f0b001f;
        public static final int ComposerLight = 0x7f0b0020;
        public static final int tw__Button = 0x7f0b01d8;
        public static final int tw__ButtonBar = 0x7f0b01da;
        public static final int tw__Button_Light = 0x7f0b01d9;
        public static final int tw__CardAppInfoLayout = 0x7f0b01db;
        public static final int tw__CardAppName = 0x7f0b01dc;
        public static final int tw__CardAppStoreName = 0x7f0b01dd;
        public static final int tw__CardInstallButton = 0x7f0b01de;
        public static final int tw__ComposerAvatar = 0x7f0b01e0;
        public static final int tw__ComposerCharCount = 0x7f0b01e1;
        public static final int tw__ComposerCharCountOverflow = 0x7f0b01e2;
        public static final int tw__ComposerClose = 0x7f0b01e3;
        public static final int tw__ComposerDivider = 0x7f0b01e4;
        public static final int tw__ComposerToolbar = 0x7f0b01e5;
        public static final int tw__ComposerTweetButton = 0x7f0b01e6;
        public static final int tw__EditTweet = 0x7f0b01e7;
        public static final int tw__Permission_Container = 0x7f0b01e8;
        public static final int tw__Permission_Description = 0x7f0b01e9;
        public static final int tw__Permission_Title = 0x7f0b01ea;
    }
    public static final class styleable {
        public static final int[] tw__AspectRatioImageView = { 0x7f0101b3, 0x7f0101b4 };
        public static final int tw__AspectRatioImageView_tw__image_aspect_ratio = 0;
        public static final int tw__AspectRatioImageView_tw__image_dimension_to_adjust = 1;
    }
}
